# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f4a1318ea235018b6ce715f9969eee2"
name = "Khakan Connect Dev"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_locations,write_orders,write_fulfillments"

use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
