client_id = "8f4a1318ea235018b6ce715f9969eee2"
name = "Khakan Connect Dev"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "read_locations,read_orders,read_products,write_fulfillments,write_orders"

use_legacy_install_flow = false

[auth]
redirect_urls = []

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "khakan-fulfillment-2.myshopify.com"
